name: Create 2026 Event Discussions

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions to allow creating discussions
permissions:
  contents: read
  discussions: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  create-discussions:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3fe9b3ae632c6758d0b7757b0838606ef4287b08
        with:
          bb: 1.12.194

      - name: Create discussions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd feeds
          bb src/madison_clojure/create_discussions.clj
